#config for 3D slicer extension
NORM = True
PREPROCESSING= True

IMAGE_HEIGHT = 40
IMAGE_WIDTH = 40
IMAGE_DEPTH = 40

IMG_SIZE = (IMAGE_HEIGHT, IMAGE_WIDTH,IMAGE_DEPTH)
HOUNSFIELD_MIN = -1000
HOUNSFIELD_MAX = 4000
HOUNSFIELD_RANGE = HOUNSFIELD_MAX - HOUNSFIELD_MIN